export const showPost = state => state.showPost
export const galleryImgs = state => state.galleryImgs
export const galleryIndex = state => state.galleryIndex
export const token = state => state.token
export const uid = state => state.uid
export const avatar = state => state.avatar
export const username = state => state.username
export const uploadSK = state => state.uploadSK
export const following = state => state.following
export const like = state => state.like
export const favour = state => state.favour
export const recentlyMoments = state =>  state.recentlyMoments
export const momentData = state => state.momentData
export const chooseSchools = state => state.chooseSchools
