export const SET_SHOWPOST = 'SET_SHOWPOST'
export const SET_GALLERYIMGS = 'SET_GALLERYIMGS'
export const SET_GALLERYINDEX = 'SET_GALLERYINDEX'

export const SET_TOKEN = 'SET_TOKEN'
export const SET_UID = 'SET_UID'

export const SET_UPLOADSK = 'SET_UPLOADSK'

export const SET_FOLLOWING = 'SET_FOLLOWING'
export const PUSH_FOLLOWING = 'PUSH_FOLLOWING'

export const SET_FAVOUR = 'SET_FAVOUR'

export const SET_LIKE = 'SET_LIKE'
export const PUSH_LIKE = 'PUSH_LIKE'
export const PULL_LIKE = 'PULL_LIKE'

export const SET_RECENTLY_MOMENTS = 'SET_RECENTLY_MOMENTS'
export const PUSH_RECENTLY_MOMENTS = 'PUSH_RECENTLY_MOMENTS'
export const PULL_RECENTLY_MOMENTS = 'PULL_RECENTLY_MOMENTS'