export const SET_SHOWPOST = 'SET_SHOWPOST'
export const SET_GALLERYIMGS = 'SET_GALLERYIMGS'
export const SET_GALLERYINDEX = 'SET_GALLERYINDEX'

export const SET_TOKEN = 'SET_TOKEN'
export const SET_UID = 'SET_UID'

export const SET_UPLOADSK = 'SET_UPLOADSK'